#include <opencv2/core.hpp>

struct rectHash{
    std::size_t operator()(const cv::Rect& rect) const {
        std::hash<int> hashVal;
        return hashVal(static_cast<int>(floor(rect.x / rect.width) + floor(rect.y / rect.height)));
  }
};

struct rectEqual{
    bool operator() (const cv::Rect& l, const cv::Rect& r) const {
        return l.x == r.x && l.y == r.y &&
               l.width == r.width &&
               l.height == r.height;
    }
};

const std::vector<std::string> ACTIONS_MAP  =  {"hello",
                                                "nice",
                                                "teacher",
                                                "eat",
                                                "no",
                                                "happy",
                                                "like",
                                                "orange",
                                                "want",
                                                "deaf",
                                                "school",
                                                "sister",
                                                "finish",
                                                "white",
                                                "bird",
                                                "what",
                                                "tired",
                                                "friend",
                                                "sit",
                                                "mother",
                                                "yes",
                                                "student",
                                                "learn",
                                                "spring",
                                                "good",
                                                "fish",
                                                "again",
                                                "sad",
                                                "table",
                                                "need",
                                                "where",
                                                "father",
                                                "milk",
                                                "cousin",
                                                "brother",
                                                "paper",
                                                "forget",
                                                "nothing",
                                                "book",
                                                "girl",
                                                "fine",
                                                "black",
                                                "boy",
                                                "lost",
                                                "family",
                                                "hearing",
                                                "bored",
                                                "please",
                                                "water",
                                                "computer",
                                                "help",
                                                "doctor",
                                                "yellow",
                                                "write",
                                                "hungry",
                                                "but",
                                                "drink",
                                                "bathroom",
                                                "man",
                                                "how",
                                                "understand",
                                                "red",
                                                "beautiful",
                                                "sick",
                                                "blue",
                                                "green",
                                                "english",
                                                "name",
                                                "you",
                                                "who",
                                                "same",
                                                "nurse",
                                                "day",
                                                "now",
                                                "brown",
                                                "thanks",
                                                "hurt",
                                                "here",
                                                "grandmother",
                                                "pencil",
                                                "walk",
                                                "bad",
                                                "read",
                                                "when",
                                                "dance",
                                                "play",
                                                "sign",
                                                "go",
                                                "big",
                                                "sorry",
                                                "work",
                                                "draw",
                                                "grandfather",
                                                "woman",
                                                "right",
                                                "france",
                                                "pink",
                                                "know",
                                                "live",
                                                "night"};

